name: Build and Run

on:
  pull_request:
    branches: [ main ]

env:
  CMAKE_BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows x86-64",
            os: windows-latest,
            run: build\Release\nox.exe,
            docker: winget install DockerDesktop && docker\run.bat,
          }
          - {
            name: "Ubuntu x86_64",
            os: ubuntu-latest,
            run: ./build/nox,
            docker: apt install docker.io && sudo service docker status && ./docker/run.sh,
          }
          - {
            name: "MacOSX x86_64",
            os: macos-latest,
            run: ./build/nox,
            docker: brew install -cask docker && sudo systemctl start docker && ./docker/run.sh,
          }
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    steps:
      # Fetch our repository.
      - uses: actions/checkout@v2

      # Create our build directory.
      - name: Create build directory
        run: mkdir build

      # Change to our build directory and run cmake.
      - name: Configure
        working-directory: ./build
        run: cmake ..

      # Build the project.
      - name: Build
        working-directory: ./build
        run: cmake --build .

      # Change to our project root run the executable.
      - name: Run
        working-directory: .
        run: ${{ matrix.config.run }}

      - name: Run docker
        run: ${{ matrix.config.docker }}
