name: Build and Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  Build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows/Static/X64/Release",
            os: windows-latest,
            config: Release,
            args: -G "Visual Studio 16 2019" -A x64,
          }
          - {
            name: "Ubuntu/18.04/Static/X64/Release",
            os: ubuntu-latest,
            config: Release,
            cmake_extra_args: "-DCMAKE_C_COMPILER=/usr/bin/gcc-10",
          }
          - {
            name: "MacOSX/Static/X64/Release",
            os: macos-latest,
            config: Release,
            args: "",
          }
    steps:
      - uses: actions/checkout@v2

      - name: Create build directory
        run: mkdir build

      - name: Configure
        working-directory: ./build
        run: cmake .. ${{ matrix.config.cmake_extra_args }} -DCMAKE_BUILD_TYPE=${{ matrix.config.config }}

      - name: Build
        working-directory: ./build
        run: cmake --build . -j --config ${{ matrix.config.config }}

      - name: Run Windows
        if: ${{ matrix.config.os == 'windows-latest' }}
        working-directory: .
        run: build\Release\nox.exe

      - name: Run Unix
        if: ${{ matrix.config.os != 'windows-latest' }}
        working-directory: .
        run: ./build/nox
